name = "webtoon-tier-cloudflare"
compatibility_date = "2026-05-09"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "webtoon-tier-db"
database_id = "d578ee1f-ad00-450b-b00a-ee26f2a6fa57"

